- name: Install Apache
  hosts: all
  
  tasks:
  - name: Install the latest version of Apache
    yum:
      name: httpd
      state: latest
  - name: Enable and start Apache service
    service:
      name: httpd
      enabled: yes
      state: started