- name: Create Demo File
  hosts: all
  vars:
    demo_message: "Default message"
  
    tasks:
    - name: Demo File
      copy:
        content: "{{ demo_message }}"
        dest: "ansible_demo_file.txt"